name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1

      - name: Nuget Restore
        run: nuget restore

      - name: Build .Net9
        run: msbuild /t:AssetStudio_GUI:publish /p:Configuration=Release /p:TargetFramework=net9.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Build .Net9 CLI
        run: msbuild /t:AssetStudio_CLI:publish /p:Configuration=Release /p:TargetFramework=net9.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Upload .Net9 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net9.0-${{ github.sha }}
          path: AssetStudio.GUI/bin/Release/net9.0-windows/publish

      - name: Upload .Net9 CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net9.0-cli-${{ github.sha }}
          path: AssetStudio.CLI/bin/Release/net9.0-windows/publish
